## CHANGE this to the name of your plugin.
name: AdvancedTech

## CHANGE this to your username.
author: pranavverma

## CHANGE this to a meaninful but short description of your plugin.
description: A Addon to add Exiting New Machines to SlimeFun.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.pranavverma.advancedtech.AdvancedTech

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://web.craftingrealm.tk

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.o
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.17

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
